### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jamesduncan**

### CODE REVIEW

**Comment by jamesduncan** [comment]
@wongpratan Before we merge this do we need to make changes to any date/datetime fields?

**Comment by Hiro-Nakamura** [comment]
On my initial pass through, it looks good to me.  

Hard to really gauge on such a large commit.  But this is all working well on #develop ?

**Comment by jamesduncan** [comment]
We are ready to get code moved to master for a release...anyone have any objections?

**Comment by jamesduncan** [comment]
When we move this over? Will the subrepos be pointing to develop? This part of the process is a little tricky for me to wrap my mind around.

**Pull request merged**
