### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jamesduncan**

### CODE REVIEW

**Review by Hiro-Nakamura — CHANGES_REQUESTED** [review]
OK, there has been a lot of changes here.  

I've gone through initially and caught a few things.  Please fix them before we merge.

**Comment by Hiro-Nakamura** [comment]
I would also like to leave a Friendly Reminder that any new changes made to components outside of the `core` repo, needs to make sure they also end up in the `v2` branch.  

I'm no longer going through and merging in these changes, as I'm focusing on getting things up and running.  

There is a lot here that needs to be pulled over.

**Review by wongpratan — APPROVED** [review]

**Comment by jamesduncan** [comment]
Okay are we ready to merge?? We need to start with core first right?

**Comment by Hiro-Nakamura** [comment]
merge core ... then when this gets merged in, we also need to make sure the merge includes the updated Core reference

**Pull request merged**
